### ISSUE TITLE
🐞 Bug Kraken - Unfortunately we could not generate the static pairlist

### ISSUE THREAD

**Issue by El-Castor** [Rikj000/MoniGoMani#255]
Hi ! 
First thanks a lot for your framework !

I am trying to download static pairlist in order to do hyperopt and backtesting using data from Kraken exchange. 

Operating system: Mac osx 10.15.4

python3 --version:
Python 3.8.5

Freqtrade Version: freqtrade --version:
freqtrade 23.4.17

```json
{
    "monigomani_settings": {
        "timeframes": {
            "backtest_timeframe": "5m",
            "core_trend_timeframe": "4h",
            "roi_timeframe": "2h",
            "timeframe": "30m"
        },
        "startup_candle_count": 400,
        "precision": 1,
        "trading_during_trends": {
            "buy_trades_when_downwards": true,
            "buy_trades_when_sideways": true,
            "buy_trades_when_upwards": true,
            "sell_trades_when_downwards": true,
            "sell_trades_when_sideways": true,
            "sell_trades_when_upwards": true
        },
        "weighted_signal_spaces": {
            "sell_profit_only": true,
            "min_weighted_signal_value": 0,
            "max_weighted_signal_value": 100,
            "min_trend_total_signal_needed_value": 60,
            "min_trend_total_signal_needed_candles_lookback_window_value": 1,
            "max_trend_total_signal_needed_candles_lookback_window_value": 8,
            "min_trend_signal_triggers_needed": 2,
            "search_threshold_weighted_signal_values": 22,
            "search_threshold_trend_total_signal_needed_candles_lookback_window_value": 1,
            "search_threshold_trend_signal_triggers_needed": 1
        },
        "stoploss_spaces": {
            "stoploss_min_value": -0.02,
            "stoploss_max_value": -0.3,
            "trailing_stop_positive_min_value": 0.01,
            "trailing_stop_positive_max_value": 0.08,
            "trailing_stop_positive_offset_min_value": 0.011,
            "trailing_stop_positive_offset_max_value": 0.1
        },
        "roi_spaces": {
            "roi_delay": 120,
            "roi_table_step_size": 5,
            "roi_time_interval_scaling": 1.6,
            "roi_value_step_scaling": 0.9,
            "roi_when_downwards": true,
            "roi_when_sideways": true,
            "roi_when_upwards": false
        },
        "unclogger_spaces": {
            "unclogger_buy_cooldown_minutes_window": {
                "min": 180,
                "max": 360,
                "threshold": 20
            },
            "unclogger_enabled": true,
            "unclogger_minimal_losing_trade_duration_minutes": {
                "min": 15,
                "max": 560
            },
            "unclogger_minimal_losing_trades_open": {
                "min": 1,
                "max": 5,
                "threshold": 1
            },
            "unclogger_open_trades_losing_percentage_needed": {
                "min": 1,
                "max": 60
            },
            "unclogger_trend_lookback_candles_window": {
                "min": 10,
                "max": 60
            },
            "unclogger_trend_lookback_candles_window_percentage_needed": {
                "min": 10,
                "max": 45
            },
            "unclogger_trend_lookback_candles_window_recent_past_weight_separator": 2,
            "unclogger_trend_lookback_window_uses_downwards_candles": true,
            "unclogger_trend_lookback_window_uses_sideways_candles": true,
            "unclogger_trend_lookback_window_uses_upwards_candles": false
        },
        "protection_spaces": [
            {
                "method": "CooldownPeriod",
                "stop_duration_candles": {
                    "min": 2,
                    "max": 5,
                    "threshold": 1,
                    "type": "integer"
                }
            },
            {
                "method": "MaxDrawdown",
                "lookback_period_candles": {
                    "min": 2,
                    "max": 200,
                    "threshold": 20,
                    "type": "integer"
                },
                "trade_limit": {
                    "min": 2,
                    "max": 100,
                    "threshold": 10,
                    "type": "integer"
                },
                "stop_duration_candles": {
                    "min": 2,
                    "max": 100,
                    "threshold": 10,
                    "type": "integer"
                },
                "max_allowed_drawdown": {
                    "min": 0,
                    "max": 1,
                    "threshold": 0.1,
                    "type": "decimal"
                }
            },
            {
                "method": "StoplossGuard",
                "lookback_period_candles": {
                    "min": 2,
                    "max": 200,
                    "threshold": 20,
                    "type": "integer"
                },
                "trade_limit": {
                    "min": 2,
                    "max": 100,
                    "threshold": 10,
                    "type": "integer"
                },
                "stop_duration_candles": {
                    "min": 2,
                    "max": 100,
                    "threshold": 10,
                    "type": "integer"
                },
                "only_per_pair": false
            },
            {
                "method": "StoplossGuard",
                "id": "PerPair",
                "lookback_period_candles": {
                    "min": 2,
                    "max": 200,
                    "threshold": 20,
                    "type": "integer"
                },
                "trade_limit": {
                    "min": 2,
                    "max": 100,
                    "threshold": 10,
                    "type": "integer"
                },
                "stop_duration_candles": {
                    "min": 2,
                    "max": 100,
                    "threshold": 10,
                    "type": "integer"
                },
                "only_per_pair": true
            },
            {
                "method": "LowProfitPairs",
                "id": "1",
                "lookback_period_candles": {
                    "min": 2,
                    "max": 200,
                    "threshold": 20,
                    "type": "integer"
                },
                "trade_limit": {
                    "min": 2,
                    "max": 100,
                    "threshold": 10,
                    "type": "integer"
                },
                "stop_duration_candles": {
                    "min": 2,
                    "max": 100,
                    "threshold": 10,
                    "type": "integer"
                },
                "required_profit": {
                    "min": 0,
                    "max": 1,
                    "threshold": 0.1,
                    "type": "decimal"
                }
            },
            {
                "method": "LowProfitPairs",
                "id": "2",
                "lookback_period_candles": {
                    "min": 2,
                    "max": 200,
                    "threshold": 20,
                    "type": "integer"
                },
                "trade_limit": {
                    "min": 2,
                    "max": 100,
                    "threshold": 10,
                    "type": "integer"
                },
                "stop_duration_candles": {
                    "min": 2,
                    "max": 100,
                    "threshold": 10,
                    "type": "integer"
                },
                "required_profit": {
                    "min": 0,
                    "max": 1,
                    "threshold": 0.1,
                    "type": "decimal"
                }
            }
        ],
        "default_stub_values": {
            "minimal_roi": {
                "0": 100
            },
            "stoploss": -1,
            "trailing_stop": false,
            "trailing_stop_positive": 0.01,
            "trailing_stop_positive_offset": 0.03,
            "trailing_only_offset_is_reached": false
        },
        "debuggable_weighted_signal_dataframe": true,
        "use_mgm_logging": false,
        "mgm_log_levels_enabled": {
            "info": true,
            "warning": true,
            "error": true,
            "debug": true,
            "custom": true
        }
    },
    "monigomani_hyperoptloss_settings": {
        "average_duration": {
            "average_duration_weight": 75,
            "expected_average_duration_minutes": 300,
            "average_duration_threshold_high": 600,
            "average_duration_threshold_low": 120
        },
        "average_profit": {
            "average_profit_weight": 100,
            "expected_average_profit": 1.5,
            "average_profit_threshold_high": 3,
            "average_profit_threshold_low": 0.5
        },
        "max_drawdown": {
            "max_drawdown_weight": 75,
            "expected_max_drawdown": 90,
            "max_drawdown_threshold_high": 150,
            "max_drawdown_threshold_low": 30
        },
        "total_profit": {
            "total_profit_weight": 200,
            "expected_total_profit": 70,
            "total_profit_threshold_high": 100,
            "total_profit_threshold_low": 30
        },
        "total_trades": {
            "total_trades_weight": 100,
            "expected_total_trades": 500,
            "total_trades_threshold_high": 1000,
            "total_trades_threshold_low": 100
        },
        "win_ratio": {
            "win_ratio_weight": 100,
            "expected_win_ratio": 70,
            "win_ratio_threshold_high": 90,
            "win_ratio_threshold_low": 50
        }
    },
    "dry_run": true,
    "dry_run_wallet": 500,
    "max_open_trades": -1,
    "stake_currency": "USDT",
    "stake_amount": 45,
    "tradable_balance_ratio": 0.99,
    "amount_reserve_percent": 0.05,
    "amend_last_stake_amount": false,
    "last_stake_amount_min_ratio": 0.5,
    "cancel_open_orders_on_exit": false,
    "use_sell_signal": true,
    "sell_profit_only": false,
    "sell_profit_offset": 0,
    "ignore_roi_if_buy_signal": true,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 30,
        "unit": "minutes"
    },
    "bid_strategy": {
        "price_side": "bid",
        "use_order_book": true,
        "ask_last_balance": 0,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 0.95
        }
    },
    "ask_strategy": {
        "price_side": "ask",
        "use_order_book": true,
        "order_book_top": 1
    },
    "order_types": {
        "buy": "limit",
        "sell": "limit",
        "emergencysell": "market",
        "forcesell": "market",
        "forcebuy": "market",
        "stoploss": "market",
        "stoploss_on_exchange": false,
        "stoploss_on_exchange_interval": 60
    },
    "order_time_in_force": {
        "buy": "gtc",
        "sell": "gtc"
    },
    "exchange": {
        "sandbox": false,
        "ccxt_config": {
            "enableRateLimit": true
        },
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 500,
            "aiohttp_trust_env": false
        },
        "pair_blacklist": [
            ".*USD.*/.*",
            ".*BULL.*/.*",
            ".*BEAR.*/.*",
            ".*UP.*/.*",
            ".*DOWN.*/.*",
            ".*HEDGE.*/.*",
            ".*PREMIUM.*/.*",
            ".*PERP.*/.*",
            ".*/BNB",
            "BNB/.*",
            "EPS/.*",
            "EUR/.*",
            "GBP/.*"
        ],
        "outdated_offset": 5,
        "markets_refresh_interval": 60,
        "pair_whitelist": false
    },
    "pairlists": [
        {
            "method": "StaticPairList"
        }
    ],
    "_pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 60,
            "sort_key": "quoteVolume",
            "refresh_period": 1800
        },
        {
            "method": "AgeFilter",
            "min_days_listed": 7
        },
        {
            "method": "SpreadFilter",
            "max_spread_ratio": 0.005
        },
        {
            "method": "PriceFilter",
            "low_price_ratio": 0.001
        },
        {
            "method": "RangeStabilityFilter",
            "lookback_days": 3,
            "min_rate_of_change": 0.1,
            "refresh_period": 1440
        },
        {
            "method": "VolatilityFilter",
            "lookback_days": 4,
            "min_volatility": 0.02,
            "max_volatility": 0.75,
            "refresh_period": 86400
        },
        {
            "method": "VolumePairList",
            "number_assets": 10,
            "sort_key": "quoteVolume"
        }
    ],
    "initial_state": "running",
    "forcebuy_enable": false,
    "internals": {
        "process_throttle_secs": 5,
        "heartbeat_interval": 60
    },
    "disable_dataframe_checks": false,
    "strategy_path": "user_data/strategies/",
    "dataformat_ohlcv": "json",
    "dataformat_trades": "jsongz"
}
```

running command:

```bash
sudo  python3 -m pipenv run python3 ./mgm-hurry download_static_pairlist
```

Terminal Error :

```bash
CRITICAL - Unfortunately we could generate the static pairlist.
INFO - 🤖 Saving fresh static pairlist into mgm_pair_lists/Kraken-USDT-Top-Volume-StaticPairList.json
INFO - 🍺 Saving pairlist as whitelist to "mgm-config.json"...
```
with above this message error :
```bash
ERROR - Could not load tickers due to ExchangeError. Message: kraken GET https://api.kraken.com/0/public/Ticker?pair=1INCHE ....
```
Do you have any Id why I cannot load ticker ?

Thanks in advance

**Comment by SybrandDoev** [comment]
Hi,

This is a configuration error.

You are using the StaticPairList method, which uses a statically defined pair whitelist from the configuration.
You are trying to use volume pair list in your config to create a static pairlist. That's nog the way to do this.

You have to choose. If you don't want the volume pair list to refresh and possibly change, generate a static pairlist with;

```
mgm-hurry download_static_pairlist
```

If you want a volumepairlist, created at the moment you load your config (and refreshing every x amount of minutes) use something like

```
"pairlists": [
    {
        "method": "VolumePairList",
        "number_assets": 20,
        "sort_key": "quoteVolume",
        "min_value": 0,
        "refresh_period": 1800
    }
],
```

More info: https://www.freqtrade.io/en/stable/plugins/

**Comment by SybrandDoev** [comment]
And if that's not the case, look at the static pairlist already saved. Did you make it yourself? 1INCHE doesn't look valid to me.

But the false after pair whitelist is most likely giving problems I guess..

**Comment by El-Castor** [comment]
Hi SybrandDoev,

Thanks for your quick response. I didn't build the static pair list by myself, because I use mgm-hurry up command and I say yes for do the configuration following the instructions provide.

I will change my config by hand by maybe I didn't get something, but I have a question, It is not should be create/build by the framework right ? I mean when I follow these instruction :

```bash
 _ __ ___    __ _  _ __ ___         | |__   _   _  _ __  _ __  _   _ 
| '_ ` _ \  / _` || '_ ` _ \  _____ | '_ \ | | | || '__|| '__|| | | |
| | | | | || (_| || | | | | ||_____|| | | || |_| || |   | |   | |_| |
|_| |_| |_| \__, ||_| |_| |_|       |_| |_| \__,_||_|   |_|    \__, |
            |___/                                              |___/ 

INFO - 💨 💨 💨
       👉 The all in one command. Hurry up, turn it up!
       💨 💨 💨
? 💨 Do you want to update Freqtrade? No
? 💨 Do you want to update MoniGoMani? No
? 💨 Do you want to configure it now? Yes
? 💨 Do you want to generate a static pairlist now? Yes
? 💨 Do you want to download candle data now? Yes
? 💨 Do you want to hyperopt now? No
? 💨 Do you want to backtest now? No
? 💨 Do you want to start trading? Yes, Dry-Run please
INFO - 💨 💨 💨
       👉 Setup
       💨 💨 💨
INFO - 🤓 Let's answer some questions to make your life easier.
WARNING - ⚠️ The target file "mgm-config.json" already exists. Is cool.
WARNING - ⚠️ The target file "mgm-config-private.json" already exists. Is cool.
INFO - 👉 MoniGoMani config files prepared √
? Please enter the default timerange you want to use: 20210501-20210616
? Which HyperOpt Strategy do you want to use? MoniGoManiHyperStrategy
? Which HyperOpt Loss do you want to use? MGM_SortinoHyperOptLoss
? Which spaces do you want to HyperOpt? ['buy', 'sell']
? Please enter the default stake currency you want to use: USDT
? Please enter the amount of epochs you want to HyperOpt: 1000
? Do you want to also setup your exchange? Yes
? Which exchange do you want to use? kraken
? Please enter the exchange API key:  ********************************************************
? Please enter the exchange API secret:  ****************************************************************************************
? Please enter the username you want to use to share test results with the MoniGoMani community: johnyMalza
INFO - 🍺 Configuration data written to ".hurry" file
INFO - 🍺 Exchange settings written to "mgm-config-private.json"
? Do you want to also setup your Telegram bot?  No
INFO - 💨 💨 💨
       👉 Download Top Volume Static Pairlist
       💨 💨 💨
INFO - 🤖 Generating new static pairlist...
? How much pairs would you like in your TopVolumeStaticPairList? (1 - 200) 15
````
Because following these instruction, the config file should be build for static pair list right? The fact is that I have the previous error as you can see below :

```bash
INFO - 🤖 Generating new static pairlist...
? How much pairs would you like in your TopVolumeStaticPairList? (1 - 200) 15
INFO - 👉 Added 9 extra days to the timerange for the "startup_candle_count"
INFO - 👉 MGM-Hurry will now run the following command for you:
 . /Users/macbook/Development/Freqtrade-MGM/.env/bin/activate; freqtrade test-pairlist --config /Users/macbook/Development/Freqtrade-MGM/user_data/mgm_tools/RetrieveTopVolumeStaticPairList.json --quote USDT --print-json > /tmp/tmpqrk8v63q
INFO - Using config: /Users/macbook/Development/Freqtrade-MGM/user_data/mgm_tools/RetrieveTopVolumeStaticPairList.json ...
INFO - Verbosity set to 0
INFO - Using user-data directory: /Users/macbook/Development/Freqtrade-MGM/user_data ...
INFO - Using data directory: /Users/macbook/Development/Freqtrade-MGM/user_data/data/kraken ...
INFO - Checking exchange...
INFO - Exchange "kraken" is officially supported by the Freqtrade development team.
INFO - Using pairlist from configuration.
INFO - Validating configuration ...
INFO - Instance is running with dry_run enabled
INFO - Using CCXT 1.61.92
INFO - Applying additional ccxt config: {'enableRateLimit': True}
INFO - Applying additional ccxt config: {'enableRateLimit': True}
INFO - Using Exchange "Kraken"
INFO - Using resolved exchange 'Kraken'...
INFO - Using resolved pairlist VolumePairList from '/Users/macbook/Development/Freqtrade-MGM/freqtrade/plugins/pairlist/VolumePairList.py'...
INFO - Using resolved pairlist AgeFilter from '/Users/macbook/Development/Freqtrade-MGM/freqtrade/plugins/pairlist/AgeFilter.py'...
INFO - Using resolved pairlist PriceFilter from '/Users/macbook/Development/Freqtrade-MGM/freqtrade/plugins/pairlist/PriceFilter.py'...
INFO - Using resolved pairlist ShuffleFilter from '/Users/macbook/Development/Freqtrade-MGM/freqtrade/plugins/pairlist/ShuffleFilter.py'...
INFO - Using resolved pairlist SpreadFilter from '/Users/macbook/Development/Freqtrade-MGM/freqtrade/plugins/pairlist/SpreadFilter.py'...
INFO - Using resolved pairlist RangeStabilityFilter from '/Users/macbook/Development/Freqtrade-MGM/freqtrade/plugins/pairlist/rangestabilityfilter.py'...
INFO - Using resolved pairlist VolatilityFilter from '/Users/macbook/Development/Freqtrade-MGM/freqtrade/plugins/pairlist/VolatilityFilter.py'...
INFO - Using resolved pairlist VolumePairList from '/Users/macbook/Development/Freqtrade-MGM/freqtrade/plugins/pairlist/VolumePairList.py'...
WARNING - get_tickers() returned exception: "Could not load tickers due to ExchangeError. Message: kraken GET https://api.kraken.com/0/public/T


```

**Comment by El-Castor** [comment]
Hi!

I have try to change the differents config files as you preconise but still have the same error. 

here is my mgm-config.son file part related to pairlists and exchange:

```json
    "exchange": {
        "pair_whitelist": [],
        "sandbox": false,
        "ccxt_config": {
            "enableRateLimit": true
        },
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 500,
            "aiohttp_trust_env": false
        },
        "pair_blacklist": [
            ".*USD.*/.*",
            ".*BULL.*/.*",
            ".*BEAR.*/.*",
            ".*UP.*/.*",
            ".*DOWN.*/.*",
            ".*HEDGE.*/.*",
            ".*PREMIUM.*/.*",
            ".*PERP.*/.*",
            ".*/BNB",
            "BNB/.*",
            "EPS/.*",
            "EUR/.*",
            "GBP/.*"
        ],
        "outdated_offset": 5,
        "markets_refresh_interval": 60
    },
    "pairlists": [
        {
            "method": "StaticPairList"
        }
    ],
    "_pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 60,
            "sort_key": "quoteVolume",
            "refresh_period": 1800
        },
        {
            "method": "AgeFilter",
            "min_days_listed": 7
        },
        {
            "method": "SpreadFilter",
            "max_spread_ratio": 0.005
        },
        {
            "method": "PriceFilter",
            "low_price_ratio": 0.001
        },
        {
            "method": "RangeStabilityFilter",
            "lookback_days": 3,
            "min_rate_of_change": 0.1,
            "refresh_period": 1440
        },
        {
            "method": "VolatilityFilter",
            "lookback_days": 4,
            "min_volatility": 0.02,
            "max_volatility": 0.75,
            "refresh_period": 86400
        },
        {
            "method": "VolumePairList",
            "number_assets": 10,
            "sort_key": "quoteVolume"
        }
    ],
```
When I am trying to download static pairlist using mgm-hurry command :
```bash
sudo  python3 -m pipenv run python3 ./mgm-hurry download_static_pairlist
```
I still have the same error. But I saw that  mgm-hurry didn't use the mgm-config.json file but another located in the directory Freqtrade-MGM/user_data/mgm_tools/RetrieveTopVolumeStaticPairList.json

Here is the file:

```json
{
    "pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 200,
            "sort_key": "quoteVolume",
            "refresh_period": 1800
        },
        {
            "method": "AgeFilter",
            "min_days_listed": 287
        },
        {
            "method": "PriceFilter",
            "low_price_ratio": 0.1
        },
        {
            "method": "ShuffleFilter"
        },
        {
            "method": "SpreadFilter",
            "max_spread_ratio": 0.005
        },
        {
            "method": "RangeStabilityFilter",
            "lookback_days": 10,
            "min_rate_of_change": 0.01,
            "refresh_period": 1440
        },
        {
            "method": "VolatilityFilter",
            "lookback_days": 5,
            "min_volatility": 0.05,
            "max_volatility": 0.5,
            "refresh_period": 1440
        },
        {
            "method": "VolumePairList",
            "number_assets": 15,
            "sort_key": "quoteVolume"
        }
    ],
    "exchange": {
        "pairlists":[],
        "name": "kraken",
        "pair_blacklist": [
            ".*USD.*/.*",
            ".*BULL.*/.*",
            ".*BEAR.*/.*",
            ".*UP.*/.*",
            ".*DOWN.*/.*",
            ".*HEDGE.*/.*",
            ".*PREMIUM.*/.*",
            ".*PERP.*/.*",
            ".*/BNB",
            "BNB/.*",
            "EPS/.*",
            "EUR/.*",
            "GBP/.*"
        ],
        "ccxt_config": {
            "enableRateLimit": true
        },
        "ccxt_async_config": {
            "enableRateLimit": true
        }
    }
}
```

I did'nt understand why I have this error and why any whitelist. I have check on the repository of the pairlist build by mgm-hurry in /user_data/mgm_pair_lists/Kraken-USDT-Top-Volume-StaticPairList.json but it is fill by false and not by pairs as the one for Binance exchange for exemple. See bellow the .json :

```json
{
    "exchange": {
        "pair_whitelist": false
    }
}
```

I followed the step-by-step recommendations of the mgm documentation available here : https://monigomani.readthedocs.io/

I think iit has a trooble during mgm-hurry setup command in order to build Kraken static pair List or I just miss something during the configuration ?

Someone can help me to resolve this problem?
Thanks

**Comment by SybrandDoev** [comment]
Hi El-Castor,

After looking deeper into it (especially in the Freqtrade GitHub), it doesn't seem to be a configuration error:

```https://github.com/freqtrade/freqtrade/issues/6311```

Reply from Matthias:
```That's a random error that appeared just this week (probably due to newly listed pairs on kraken).

you should be able to use the develop image - as this was fixed this morning in #6309.
For stable, there is currently no workaround other than using a different exchange.```

Not something we can fix here. And kraken will always have a rate limit of 3100 in stead of 500. Also read some problems with downloading trading history for the pairs. Not the easiest exchange to work with tbh.

According to ```Filter tickers on stake-currency for kraken #6309``` it has been fixed. You might want to compare your ccxt file of kraken and enter the new code. Can't promise it will work though..

```https://github.com/ccxt/ccxt/blob/master/python/ccxt/kraken.py```

**Comment by El-Castor** [comment]
Hi SybrandDoev,

Thanks for your response, I didn't it when I found on the freqtrade GitHub.

Maybe it's a newbie question, but how I can fin the good  image tag in the compose file please? Or I just have to change this file https://github.com/ccxt/ccxt/blob/master/python/ccxt/kraken.py in my Freqtrade repository ?

**Comment by SybrandDoev** [comment]
I would suggest to edit the code only for kraken. MGM needs a specific freqtrade version, so updating to the most recent when the other dependances aren't met will result in a disfunctional MGM.

And since the most recent freqtrade version - as far as I know - isn't supported, editing the kraken code might be the 'safest' option to try. @Rikj000 might have a definitive answer for that.

**Comment by El-Castor** [comment]
I have change the kraken.py file by the one suggested in the issue#6309. But I have still the same error as you can see below : 

```bash
(base) macbook@Johny-malza Freqtrade-MGM % sudo  python3 -m pipenv run python3 ./mgm-hurry download_static_pairlist
                                     _                               
 _ __ ___    __ _  _ __ ___         | |__   _   _  _ __  _ __  _   _ 
| '_ ` _ \  / _` || '_ ` _ \  _____ | '_ \ | | | || '__|| '__|| | | |
| | | | | || (_| || | | | | ||_____|| | | || |_| || |   | |   | |_| |
|_| |_| |_| \__, ||_| |_| |_|       |_| |_| \__,_||_|   |_|    \__, |
            |___/                                              |___/ 

INFO - 💨 💨 💨
       👉 Download Top Volume Static Pairlist
       💨 💨 💨
INFO - 🤖 Generating new static pairlist...
? How much pairs would you like in your TopVolumeStaticPairList? (1 - 200) 15
INFO - 👉 Added 9 extra days to the timerange for the "startup_candle_count"
INFO - 👉 MGM-Hurry will now run the following command for you:
 . /Users/macbook/Development/Freqtrade-MGM/.env/bin/activate; freqtrade test-pairlist --config /Users/macbook/Development/Freqtrade-MGM/user_data/mgm_tools/RetrieveTopVolumeStaticPairList.json --quote USDT --print-json > /tmp/tmptvlkqcwj
INFO - Using config: /Users/macbook/Development/Freqtrade-MGM/user_data/mgm_tools/RetrieveTopVolumeStaticPairList.json ...
INFO - Verbosity set to 0
INFO - Using user-data directory: /Users/macbook/Development/Freqtrade-MGM/user_data ...
INFO - Using data directory: /Users/macbook/Development/Freqtrade-MGM/user_data/data/kraken ...
INFO - Checking exchange...
INFO - Exchange "kraken" is officially supported by the Freqtrade development team.
INFO - Using pairlist from configuration.
INFO - Validating configuration ...
INFO - No Kraken specific subclass found. Using the generic class instead.
INFO - Instance is running with dry_run enabled
INFO - Using CCXT 1.61.92
INFO - Applying additional ccxt config: {'enableRateLimit': True}
INFO - Applying additional ccxt config: {'enableRateLimit': True}
INFO - Using Exchange "Kraken"
INFO - Using resolved pairlist VolumePairList from '/Users/macbook/Development/Freqtrade-MGM/freqtrade/plugins/pairlist/VolumePairList.py'...
INFO - Using resolved pairlist AgeFilter from '/Users/macbook/Development/Freqtrade-MGM/freqtrade/plugins/pairlist/AgeFilter.py'...
INFO - Using resolved pairlist PriceFilter from '/Users/macbook/Development/Freqtrade-MGM/freqtrade/plugins/pairlist/PriceFilter.py'...
INFO - Using resolved pairlist ShuffleFilter from '/Users/macbook/Development/Freqtrade-MGM/freqtrade/plugins/pairlist/ShuffleFilter.py'...
INFO - Using resolved pairlist SpreadFilter from '/Users/macbook/Development/Freqtrade-MGM/freqtrade/plugins/pairlist/SpreadFilter.py'...
INFO - Using resolved pairlist RangeStabilityFilter from '/Users/macbook/Development/Freqtrade-MGM/freqtrade/plugins/pairlist/rangestabilityfilter.py'...
INFO - Using resolved pairlist VolatilityFilter from '/Users/macbook/Development/Freqtrade-MGM/freqtrade/plugins/pairlist/VolatilityFilter.py'...
INFO - Using resolved pairlist VolumePairList from '/Users/macbook/Development/Freqtrade-MGM/freqtrade/plugins/pairlist/VolumePairList.py'...
WARNING - get_tickers() returned exception: "Could not load tickers due to ExchangeError. Message: kraken GET https://api.kraken.com/0/public/Ticker?pair=1INCHEUR%2C1INCHU
 ...
...

CRITICAL - Unfortunately we could generate the static pairlist.
INFO - 🤖 Saving fresh static pairlist into mgm_pair_lists/Kraken-USDT-Top-Volume-StaticPairList.json
INFO - 🍺 Saving pairlist as whitelist to "mgm-config.json"...

```
Do you have any idea? I am very confuse I don't understand where can the problem come from.

Other idea, we can see that : INFO - Using Exchange "Kraken" but is not should be "kraken"?

**Comment by SybrandDoev** [comment]
First let me answer your question about 'k/K'raken. If you look a few lines up, you can see that the log states that Kraken is officially supported by Freqtradem that means it recognizes kraken, with or without the caps. That shouldn't be a problem.

Second: cleaned up the topic, removed non-related my non-related answers.

And third: I'll dig into it!

**Comment by rodrigogs** [comment]
I'm having the same issue trying to use mgm-hurry on a Ubuntu docker container. Installation succeeds, but in the end freqtrade is not there :(
